version: "3.7"
services:
  node:
    image: "mazegenerator:dev"
    build: 
      context: ./docker
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "npm start"